[build]
  command = "bun run build"
  publish = "apps/nextjs/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  package = "@netlify/plugin-lighthouse"

  # optional, deploy the lighthouse report to a path under your site
  [plugins.inputs.audits]
    output_path = "reports/lighthouse.html"

[dev]
  port = 8888
  targetPort = 3000
