[build]
  command = "bun run build"
  publish = "apps/nextjs/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  package = "@netlify/plugin-lighthouse"

  # optional, deploy the lighthouse report to a path under your site
  [plugins.inputs.audits]
    output_path = "reports/lighthouse.html"

[dev]
  port = 8888
  targetPort = 3000

# According to recommendation: https://docs.netlify.com/frameworks/next-js/runtime-v4/overview/#next-js-runtime
# but not needed for now
#[[redirects]]
#from = '/_next/image/*'
#query = { q = ':quality', url = ':url', w = ':width' }
#to = '/.netlify/images?url=:url&w=:width&q=:quality'
#status = 200
#force = true

# if we want to set https://docs.netlify.com/monitor-sites/real-user-metrics/
#[[headers]]
#  for = "/*"
#  [headers.values]
#    Content-Security-Policy = "[...] script-src https://netlify-rum.netlify.app"
